[package]
name = "license"
version = "0.8.0"
authors = ["evenorog <evenorog@gmail.com>"]
description = "Provides license information from https://spdx.org."
documentation = "https://docs.rs/license"
repository = "https://github.com/evenorog/license"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["license", "spdx"]
exclude = ["/.travis.yml", "/license.svg", "/run"]
edition = "2018"

[dependencies]
