[package]
name = "license"
version = "1.1.7"
authors = ["evenorog <evenorog@gmail.com>"]
description = "Provides embedded license information from SPDX."
documentation = "https://docs.rs/license"
repository = "https://github.com/evenorog/license"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["license", "spdx"]
categories = ["no-std"]
exclude = ["/.travis.yml", "/run", "/license-list-data"]
edition = "2018"

[badges]
travis-ci = { repository = "evenorog/license" }
maintenance = { status = "actively-developed" }
