[package]
name = "run"
version = "0.2.0"
authors = ["evenorog <evenorog@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
