name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Check for new tag in submodule
        id: check_tags
        run: |
          echo "OLD_TAG=$(git describe --abbrev=0)" >> "$GITHUB_ENV"
          echo "NEW_TAG=$(git -C license-list-data describe --abbrev=0)" >> "$GITHUB_ENV"
        shell: bash
      - run: |
          echo "Old tag: $OLD_TAG"
          echo "New tag: $NEW_TAG"
      - run: cargo test --verbose
        if: "$OLD_TAG" != "$NEW_TAG"
